### ISSUE TITLE
Empty dataset metadata form

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#556] opened 2020-04-20 15:48 UTC
https://data.dev.catalogue.life/dataset/31451/meta

**Comment by thomasstjerne** [comment] 2020-04-21 09:21
Duplicate of https://github.com/CatalogueOfLife/backend/issues/688

**Comment by mdoering** [comment] 2020-04-21 11:45
a search is used to populate the metadata form? No, it is a backend issue, but not the one listed above (which is for search only)

**Comment by thomasstjerne** [comment] 2020-04-21 13:21
Oops, I was wrong

**Comment by thomasstjerne** [comment] 2020-04-21 14:48
Hmm. This is a tricky one. It is because this dataset contributes to a private project. When the UI tries to fetch the projects, one fail. 
Should I swallow the error and just list the key of that dataset, or should the backend give a reduced response (only key and title) ?

This probably breaks other things as well, anywhere a list of contributeTo is given, if theres a private one in there

**Comment by mdoering** [comment] 2020-04-21 15:09
fully correct would be to not expose any of the private projects a dataset contributes to - unless a user is logged in that is allowed to see them. But that will become a serious pain in the backend if there are many places where this is exposed.

Does this only affect the dataset search? We know the user there already and I can probably restrict the contributesTo to just accessible datasets.

Speaking of contributesTo - when we have many releases for a project, does it make sense to list all releases in a dataset contributesTo property? This can get very large. And we might only ever be interested in the project, not all its releases. Should we restrict contributesTo to only point to managed datasets maybe?

And for a managed dataset it would be good to list all its releases. I will add a new `releasedFrom` parameter for the dataset search. Here are the current dataset key related params:

```
  /**
   * Filters release datasets by their parent project.
   * Automatically also restricts datasets to origin=released
   */
  @QueryParam("releasedFrom")
  private Integer releasedFrom;

  /**
   * Filters datasets to only list those that contribute as a source dataset with at least one sector to a given project.
   */
  @QueryParam("contributesTo")
  private Integer contributesTo;

  /**
   * Filters datasets by having at least one sector with a given source datasetKey.
   * Sectors only exist for managed but also released datasets.
   */
  @QueryParam("sourceDatasetKey")
  private Integer sourceDatasetKey;

  /**
   * Filters datasets by having the given editor key authorized.
   */
  @QueryParam("editor")
  private Integer editor;
```


`sourceDatasetKey` sticks out and is the opposite of `contributesTo`. I would prefer to rename that to `hasSourceDataset` but maybe both params should be called similar?

`hasSourceDataset` and `sourceDatasetOf` maybe to indicate the reverse direction?

**Comment by thomasstjerne** [comment] 2020-04-21 15:17
I think it only affects this issue (meta data) and the dataset search. I have implemented frontend code that will handle possible auth errors from contributesTo list and omit those that fail.
This will prevent the UI from breaking, but it of course users who have the permission should see the private ones also

**Closed** 2020-04-21 15:17 UTC
Labels: bug
