### ISSUE TITLE
dataset link broken

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#451] opened 2019-12-12 11:40 UTC
I cannot open a simple dataset link anymore, only from within the app but not starting the application with https://data.catalogue.life/dataset/1006

**Comment by thomasstjerne** [comment] 2020-01-03 08:56
Currently everything is catalogue scoped so the dataset link only exists in the context of a catalogue: https://data.catalogue.life/catalogue/3/dataset/1006

**Comment by thomasstjerne** [comment] 2020-03-18 16:13
Duplicate of https://github.com/CatalogueOfLife/clearinghouse-ui/issues/460

**Closed by thomasstjerne** 2020-03-18 16:13 UTC
Labels: design
