### ISSUE TITLE
Source dataset not populated in sector view

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#555] opened 2020-04-17 22:03 UTC
filtered correctly, but the dataset is not shown in the form:

https://data.dev.catalogue.life/catalogue/31450/sector?limit=100&offset=0&subjectDatasetKey=31453

**Comment by thomasstjerne** [comment] 2020-04-20 09:40
Duplicate of #482

**Closed by thomasstjerne** 2020-04-20 09:40 UTC
