### ISSUE TITLE
White screen after switch to Edit metadata 

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/clearinghouse-ui#724] opened 2020-09-22 20:51 UTC
Frontend version: 2da7a94 September 22, 2020 9:53 AMBackend version: e722958 September 22, 2020 1:32 PM
https://data.catalogue.life/

I need to edit version in World Plants. 
Step 1. Searched for World Plants. Go to Metadata.
![image](https://user-images.githubusercontent.com/28574252/93935915-fd462180-fcea-11ea-8b62-93ca3f7187f6.png)

Step 2. Switched "Edit". Got white screen:
![image](https://user-images.githubusercontent.com/28574252/93935968-18b12c80-fceb-11ea-86df-7534eaa0233c.png)

**ctrl+shift+k web console says:**

This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. data.catalogue.life
false index.js:71:44
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features! data.catalogue.life
Uncaught TypeError: e is undefined
    J List.js:77
    r useScrollTo.js:40
    current useScrollTo.js:87
List.js:77:13
false index.js:71:44
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BfamilyName%2C%20name%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 10
    unstable_runWithPriority scheduler.production.min.js:19
    React 5
react-dom.production.min.js:209:194
Uncaught Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BfamilyName%2C%20name%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 10
    unstable_runWithPriority scheduler.production.min.js:19
    React 5
        Ut
        Gt
        qt
        m
        _e

![image](https://user-images.githubusercontent.com/28574252/93936587-fff54680-fceb-11ea-9c8e-1731073fbb52.png)

**Comment by yroskov** [comment] 2020-09-22 20:57
The same white screen appear with each attempt to edit metadata for other databases as well.

**Comment by mdoering** [comment] 2020-09-22 22:50
Yes, @thomasstjerne has reported in todays call that the metadata forms are not working right now and need a patch he is working on. I treat this as a duplicate of https://github.com/CatalogueOfLife/clearinghouse-ui/issues/723

**Closed by mdoering** 2020-09-22 22:50 UTC
