### ISSUE TITLE
Add all dataset menu items to the catalogue source dataset sub-menu

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/clearinghouse-ui#524] opened 2020-03-31 15:27 UTC
As discussed on the call, workflows would be more efficient if all of the dataset menu items were included in the source dataset sub-menu within a catalogue (Metadata, Imports, Classification, Names, References, Verbatim, Sectors). Otherwise, to get to those pages the user has to go dig through other menus to edit metadata, view statistics, etc. when those dataset features really need to be quick to access within a catalogue.

If you are worried about menu redundancy, the datasets menu below could probably be collapsed or even eliminated when working within a catalogue. Possibly it might sense to even make the menus role-specific so that an editor wouldn't see the dataset menu, but a dataset owner would see that menu.

**Comment by mdoering** [comment] 2020-04-02 06:19
mostly a duplicate of #531 now

**Closed** 2020-04-02 15:45 UTC
Labels: design, enhancement
