### ISSUE TITLE
Taxon detail classification link broken

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#527] opened 2020-04-01 08:45 UTC
e.g. https://data.catalogue.life/catalogue/3/taxon/17ff8f38-8589-4224-a775-29ee70c6d93c

**Comment by thomasstjerne** [comment] 2020-04-03 13:47
Duplicate of https://github.com/CatalogueOfLife/clearinghouse-ui/issues/525

**Closed by thomasstjerne** 2020-04-03 13:47 UTC
Labels: bug
